### ISSUE TITLE
Support simple predicates push down

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#13]
# Problem Statement

Assuming a dataset with schema `primary_key: string, label: dict[string], image: Image`, if we run the query:

```
SELECT image WHERE label = "cat" Limit 20
```
We should expect that Lance does not actually scan all `image` data.  Instead, it should use the filter (`label = 'cat'`) to selectively read the `image` column.

# Desired Behavior

Use the predicate push down to reduce the scan traffic over a large column (ie.., Tensor / Image).

**Comment by changhiskhan** [comment]
This is done right?

**Comment by eddyxu** [comment]
Yep this is done.
