### ISSUE TITLE
Support Image, 2D bounding box and segmentation as Arrow extension types 

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#22]
# Problem Statement

To support rich semantic types, we can utilize Arrow's [extension types](https://arrow.apache.org/docs/cpp/api/datatype.html#extension-types). It will help us to reach to the feature parity to [Rikai](https://github.com/eto-ai/rikai) storage format. 

Questions to answers:

* Do we want to only implement the data type in Lance? 
* How should we consolidate with Rikai's type system?
* How to make the type system extensible? 
* Or should we keep the extension types out of the lance data format. `Lance` just accepts extension types?

# Desired Behavior

- [ ] Support Image type
- [ ] Bounding Box
- [ ] Segmentation
- [ ] Label?
- [ ] These objects can be SerDe transparently without manually providing schema.

**Comment by changhiskhan** [comment]
does “only implement the data type in lance” mean whether to implement arrow extension type? Or whether to implement python classes in pylance (like in rikai)?

**Comment by changhiskhan** [comment]
- Start with just image/box2d
- Separate dir and branch in lance
- Figure out whether to create separate repo/project for this
- How to not confuse early adopters but also not turn lance into a kitchen sink project like Rikai

**Comment by changhiskhan** [comment]
going to make a separate issue for Segmentation etc
