### ISSUE TITLE
limit not being respected

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/lance#225]
```python
In [1]: import lance

In [2]: uri = "s3://eto-public/datasets/coco/coco.lance"

In [3]: ds = lance.dataset(uri)

In [4]: len(ds.scanner(columns=["image_id", "annotations"], limit=10).to_table())
Out[4]: 170
```

**Comment by eddyxu** [comment]
The bug was due to `lance.io.Limit` was created for each file, makes the `Limit` counting only happens within the file scope. Due to `coco` dataset has 17 files, the total table becomes `17 x 10` = 170 rows.
