### ISSUE TITLE
Improve Pyarrow Scanner::TakeRows() 

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#230]
# Problem Statement

When we try to do point query via `scanner.take()` in python, it calls `::arrow::dataset::AsyncScanner::TakeRows()`. 
The upstream implement did not optimize for point query.

# Desired behavior

We should override this `TakeRows()` behavior to take advantage of lance layout for fast point query.

**Comment by changhiskhan** [comment]
This is done in Rust already
