### ISSUE TITLE
possible performance regression?

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/lance#292]
the second one used to be very fast but is now on par with going straight through duckdb

![image](https://user-images.githubusercontent.com/759245/200042724-6636af0b-4dd9-4daf-8667-14d4d8570c68.png)

**Comment by changhiskhan** [comment]
ds = lance.dataset('s3://eto-public/datasets/oxford_pet/oxford_pet.lance')

**Comment by changhiskhan** [comment]
CPU times is very low for the second one: not sure where the rest of its Wall time is coming from

**Comment by eddyxu** [comment]
I will check whether limit pushdown has been passed through the new versioned dataset.
