### ISSUE TITLE
[PyTorch] Expose schema evolution or versioning in PyTorch Dataset

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#358]
We could either make PyTorch Dataset subclass of `lance.Dataset`, so that the functionality is directly available, or expose `lance.Dataset` in `PyTorch dataset` via facade. 

Expected behavior:

```
model = ...
dataset = lance.pytorch.Dataset("/path/to/dataset")
for batch in dataset:
    pred = postprocess(model(batch))

dataset.merge(pred_table, ...)
```

**Comment by eddyxu** [comment]
One referencen implementation is huggingface:

```python
dataset.with_format("torch");
```

We can offer a 

```python
lance.Dataset.as("torch") # as("tf")

```
which dynamically add adaptors to the `__iter__` interface?

Main concern is to that will tight `lance.Dataset` to concrete frameworks. . 

@wdyt @changhiskhan

**Comment by changhiskhan** [comment]
We can reopen when we bring pytorch dataset back
