### ISSUE TITLE
Duckdb issues

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/lance#46]
Keep track of a list of duckdb issues to support sophon's workload. We can later decide whether we want to report these issues/feature requests to upstream.

- [ ] Duckdb does not pushdown LIMIT / OFFSET via Apache Arrow. Apache Arrow does not support LIMIT / OFFSET in Scanner in general. 
  * We might need to tune he batch size to simulate the "limit" request.
- [ ] Does not support projection over `list<struct>`

```
>>> duckdb.query("SELECT annotations.label FROM coco")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Binder Error: Cannot extract field 'label' from expression "annotations" because it is not a struct
```

- [ ] https://github.com/duckdb/duckdb/issues/1643
- [ ] https://github.com/duckdb/duckdb/issues/1940
- [ ] https://github.com/apache/arrow-datafusion/pull/2566/files

**Comment by eddyxu** [comment]
https://github.com/jorgecarleitao/arrow2/pull/1180  `arrow2` (rust) has limit pushdown for parquet
