### ISSUE TITLE
`lq query` only prints like 100 rows of data and panics with "ExecNode(Limit): channel closed"

### ISSUE THREAD

**Issue by AsadullahFarooqi** [eto-ai/lance#477]
improve the panic so the user have better understanding what's going on. maybe like "the result is exceeding # of rows" or some option where the user can change the limit.
```
asd@asd-ROG-Strix-G531GW-G531GW:~/work/rust/lance/rust$ RUST_BACKTRACE=1 ./target/debug/lq query ~/work/eto-ai/try-lance/links.lance/
ExecNode(Limit): channel closed
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: IO("ExecNode(Limit): channel closed")', src/io/exec/limit.rs:88:18
stack backtrace:
+---------+--------+--------+
| movieId | imdbId | tmdbId |
+---------+--------+--------+
| 1       | 114709 | 862    |
| 2       | 113497 | 8844   |
| 3       | 113228 | 15602  |
....
| 100     | 115907 | 11062  |
| 101     | 115734 | 13685  |
+---------+--------+--------+
```

**Comment by AsadullahFarooqi** [comment]
oops so the user can control it.
```
asd@asd-ROG-Strix-G531GW-G531GW:~/work/rust/lance/rust$ ./target/debug/lq query --help
Query the dataset

Usage: lq query [OPTIONS] <URI>

Arguments:
  <URI>  

Options:
  -n <N>      The counts of record to print [default: 100]
  -h, --help  Print help
  ```

closing it

**Comment by AsadullahFarooqi** [comment]
I think this is a genuine issue, as you can see if I give it a small limit it still panics rather than graceful ending, 2nd it doesn't print beyond 1024 records
![Screenshot from 2023-01-29 01-08-04](https://user-images.githubusercontent.com/22820358/215288711-7eee0724-f31e-4a82-bb12-e1813a645082.png)

**Comment by AsadullahFarooqi** [comment]
@eddyxu @changhiskhan

**Comment by AsadullahFarooqi** [comment]
I think this issue is related to https://github.com/eto-ai/lance/issues/456

**Comment by eddyxu** [comment]
This should already be resolved with the new I/O execution graph based on datafusion , and #635 . Feel free to reopen it if you see it again
