### ISSUE TITLE
Enable Prefetching when Limit / Offset clause is included.

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#48]
# Problem Statement

For correctness and simplicity, we disabled prefetch and parallel scan when the `LIMIT / Offset` clause is provided (#45), for easier counting the number of rows read.  We expect that to serve a web app, usually we only apply LIMIT 20-100 for pagination purpose. However, there are more opportunities to improve the I/O process and improve latency.

For example, we can still allow sequential prefetch threads happened in the background without sacrificing the correctness. Furthermore, we can use hedged read to improve parallelism as well, it needs fine-tuned schedule tho.

**Comment by changhiskhan** [comment]
We can reopen this later as needed
