### ISSUE TITLE
Create IVF_PQ index from Python SDK 

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#510]
# Problem Statement

Currently, we can build IVF_PQ index via rust Dataset API and the command line tool `lq`.
We should to expose it via python SDK as well. 

# Expected behavior

```python
d = lance.dataset(uri)
d.create_index(IVF_PQ, num_partitions=256, num_sub_vectors=16)
```

**Comment by eddyxu** [comment]
Fixed in #526

**Comment by rhkenne** [comment]
Looks awesome, how do you search the created index using (a) python and (b) duckdb ? I believe searching with DuckDB and the ability to actually filters on others columns will be a game changer

**Comment by eddyxu** [comment]
@rhkenne You are right. We are currently working on native duckdb integration https://github.com/eto-ai/lance/tree/main/integration/duckdb_lance, 

A native duckdb function will be provided (Est. in 2 weeks), tentatively with the syntax like

```sql
SELECT a, b FROM  lance_nearest('uri',  'vector_column', [1, 2,3 ,4, 5], top_k=10, nprops=50) WHERE c > 100
```

Stay tuned!

In the meantime, it is possible to use python + duckdb to achieve the same functionality. 

```
import lance

dataset = lance.dataset("uri")
table = dataset.scan(nearest={"vector_column", [1,2,3,4,5], top_k=10, nprops=50), columns=["a", "b", "c"])
duckdb.query("SELECT a, b FROM table WHERE c > 100")
```
