### ISSUE TITLE
Fix duckdb GH action failure

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#567]
DuckDB GHA is current failing, likely due to the parallel build of duckdb release binary. 

We need to look into:

1. Enable parallel build for both debug and release build.
2. Make sure the dependency is appropriately described in CMakeFile between duckdb c++ objects and `duckdb extention rust build`. 
3.  Looking into ways to reduce the build target from duckdb: what is the minimal configuration that is required to build an extension.

**Comment by dacort** [comment]
I believe the failure is due to https://github.com/duckdb/duckdb/pull/6155 being merged in and the submodules being updated, so the extra definitions in `duckdb_ext` need to get removed.

**Comment by changhiskhan** [comment]
Thanks we'll take a look! Would be super nice to bring the GHA for duckdb extension back.

If you got time for a PR to try it out that'd be amazing. If not we'll try to knock it out this weekend or next week
