### ISSUE TITLE
Support for Arrow Duration

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#577]
Arrow has a duration type: https://arrow.apache.org/docs/cpp/api/datatype.html#_CPPv48durationN8TimeUnit4typeE

Support for this should be added to Lance. 

## Type mapping
1. Add type mapping from Arrow -> Lance (https://github.com/eto-ai/lance/blob/main/rust/src/datatypes.rs#L61)
2. Add type mapping from Lance -> Arrow (https://github.com/eto-ai/lance/blob/main/rust/src/datatypes.rs#L124)
3. Add type round trip tests (https://github.com/eto-ai/lance/blob/main/rust/src/datatypes.rs#L761). Make sure to test the TimeUnit parametrization.

## Encoding / decoding
1. A duration is fixed width integer, so just use the plain encoder/decoder (https://github.com/eto-ai/lance/blob/main/rust/src/encodings/plain.rs).
2. First add a read-write unit test and verify that it fails the roundtrip.
3. Add duration type to is_fixed_stride (https://github.com/eto-ai/lance/blob/51afc0052d73ed0e537ef6b2fdf3f6059d0b5548/rust/src/arrow.rs#L77) so lance knows to use the plain encoding

## Reference

See https://github.com/eto-ai/lance/pull/584 for similar implementation for decimal 128 and 256 types

**Comment by changhiskhan** [comment]
Closed by #590
