### ISSUE TITLE
Examples of lance files for verifying different implementations

### ISSUE THREAD

**Issue by Renkai** [eto-ai/lance#58]
Since we may implement lance parser/generators in different languages (Rust/Scala/etc), a collection of lance files would be useful to test the correctness and integrality of different implements.

`s3://eto-public/datasets/oxford_pet/pet.lance` has 1GiB, too big for this reason.

**Comment by eddyxu** [comment]
This is a good call. Currently the format spec is not fully stabled yet. We should definitely offer a golden set of files for reference once we are comfortable with the spec.

In the meantime, there is a command line tool: `cpp/benchmarks/convert`, which can convert arbitrary parquet files into lance files. Lets start from there?

**Comment by changhiskhan** [comment]
@Renkai the utilities in `python/benchmarks/<dataset>/datagen.py` can now create a small dataset if you just pass in the optional `--num_rows` parameter. You can see the `test_dataset.sh` script under `python/benchmarks` for usage details.
