### ISSUE TITLE
Add cargo cache to github actions

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/lance#631]
https://github.com/actions/cache/blob/main/examples.md#rust---cargo

**Comment by Renkai** [comment]
Currently there are no `Cargo.lock`s in the repository, is it deliberately? Shall we use something else for cache key or we shall add a `Cargo.lock` in the patch with the cache?

**Comment by rockpunk** [comment]
Yeah, `Cargo.lock` should [not committed](https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries) for libraries. Also, seems like this task is already closed with eto-ai/lance#495...?

**Comment by eddyxu** [comment]
Fixed in #881
