### ISSUE TITLE
Benchmark Pet / COCO raw dataset performance

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#65]
# Problem Statement

We could keep a benchmark suite to test analytics and point query performance over ML datasets (i.e.., COCO and Oxford Pet).  Using this as baseline, to test against Lance performance.

Conceptually, the benchmarks should answer queries like the following from raw JSON / XML metadata files:

```sql
# Label distribution
SELECT label, count(1) FROM dataset GROUP BY 1

# Point query
SELECT image, label, id FROM dataset WHERE label in ("dog", "cat") LIMIT 20 OFFSET 50;
```

#  Desired Behavior

Implement a benchmark that we test baseline of raw ML dataset performance and answer the desired queries.

**Comment by changhiskhan** [comment]
just pets this week

**Comment by eddyxu** [comment]
Done with coco benchmarks as well.
