### ISSUE TITLE
Prepare Python Release

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#68]
## Release Checklist

- [x] Python CI #4 
- [x] Manylinux 2014 on Linux x86 (python 3.8 - 3.10)
- [ ] Intel / Apple Silicon release on Mac (target latest MacOS and default python3 version, which is 3.10)
- [x] NO conda
- [x] Verify that we can pip install into clean env with no `libarrow*` pre-installed
- [x] Verify we can import pyarrow and lance
- [x] Verify we can create a pyarrow dataset with lance.dataset

**Comment by changhiskhan** [comment]
after this we can make first public release on pypi.org

**Comment by eddyxu** [comment]
Should we use `https://github.com/pypa/cibuildwheel` ?
