### ISSUE TITLE
Error in writing lance from pyarrow dataset

### ISSUE THREAD

**Issue by kesavkolla** [eto-ai/lance#683]
I am trying convert a parquet file to lance and encounterd following error:

```
OSError: LanceError(Schema): FileWriter::write: unsupported data type: Timestamp(Nanosecond, None)
```

Has anyone faced similar issue?

**Comment by eddyxu** [comment]
Thanks for reporting this bug @kesavkolla . We will address it in the next release.

**Comment by changhiskhan** [comment]
@kesavkolla we're making a new release now. Please upgrade your local lance install in like 30 min or so. If it still doesn't work please let us know!
