### ISSUE TITLE
Filtering strings doesn't work

### ISSUE THREAD

**Issue by cemoody** [eto-ai/lance#694]
Not quite clear to me how PyArrow Compute functions & Lance interweave. Should I be able to use any of them? Are they re-implemented in Lance?

Regardless, I'm just trying to do a a substring match:

```python
import lance
import numpy as np
import pyarrow.compute as pc

ds = lance.dataset("2.lance")
filters = pc.match_like(pc.field("title"), "%")
ds.to_table(filter=filters, nearest={"column": "vector", "q": np.random.random(768)})
```

Gets an errror like:
```
Traceback (most recent call last):
  File "/home/chris/search/gumbase/experiments/test_lance_filters.py", line 7, in <module>
    ds.to_table(filter=filters, nearest={"column": "vector", "q": np.random.random(768)})
  File "/home/chris/.pyenv/versions/vector_search/lib/python3.8/site-packages/lance/dataset.py", line 159, in to_table
    return self.scanner(
  File "/home/chris/.pyenv/versions/vector_search/lib/python3.8/site-packages/lance/dataset.py", line 102, in scanner
    ScannerBuilder(self)
  File "/home/chris/.pyenv/versions/vector_search/lib/python3.8/site-packages/lance/dataset.py", line 460, in to_scanner
    scanner = self.ds._ds.scanner(
ValueError: LanceError(I/O): sql parser error: Expected an expression:, found: {
```

**Comment by changhiskhan** [comment]
@cemoody we're adding sql string support for "like" and "in" here https://github.com/eto-ai/lance/pull/696 . Would that work for your use case (see unit test for usage)?

**Comment by cemoody** [comment]
Yeah! Anything works! I'm ambivalent whether it is SQL-style or anything else.

**Comment by cemoody** [comment]
A different filter which would be super useful, is an "allow list" filter. Basically: `id is in [1, 5, 3490, 90002]`. I'm considering a hybrid vector+bm25 search and I have already precomputed Tantivy (another Rust project) indexes alongside Lance. Passing an allow list would be a nice way to mix both retrieval engines. I'd be interesting to see if that raises my relevance.

**Comment by changhiskhan** [comment]
v0.3.16 is being released now with #696 included. Both LIKE and IN should be supported. Please give it a shot when you have time.

I'm super curious if the vector + bm25 combo is meaningfully better. if it does, potentially we could integrate tantivy as another index type at some point.

**Comment by cemoody** [comment]
Awesome. Just wrote tests on my end and verified that numeric range, string LIKE, and subset IN filters all work! Thank you!!!!

**Comment by cemoody** [comment]
re: hybrid search. 
If you are not aware, In the literature,  vector + bm25 is near-universally the strongest baseline. The difference is substantial. So much so that all of the vector search engines added BM25 search in the last few months. To everyone's surprise, hybrid search being superior continues to be true despite the last decade of AI & LLMs! Shocking that an algo from the 70s is still that good. 

A simplified but typical near-SOTA (text-only, which isn't exactly gumtap does ) search pipeline looks like:

- Retrieve with at least BM25, optionally union with a vector search
- Score both sets with TF-IDF and vector search dot products/euclidean/cosine (you might be missing one if you retrieve with the other method)
- Pass through a re-ranking model that uses BM25 and dot product scores and anything else as features. More advanced rerankers run BERT or DistillBERT  or whatever using the full query and document text to re-score the outputs and re-rank them. 

The reranker is a lot of extra complexity, and costs a lot in terms of latency, but the scores are dramatically better and results qualitatively worth it. Some vector search engines (eg vespa or weaviate) try to include this via ONNX, but I think that makes things even harder to deploy and manage. It's reason #875 why I like Lance; it has clearer separation of concerns.
