### ISSUE TITLE
The Rust crate's version is outdated in https://crates.io/crates/lance

### ISSUE THREAD

**Issue by haoxins** [eto-ai/lance#726]
https://crates.io/crates/lance/versions

The latest version is still `v0.3.8` which published `27` days ago.

**Comment by haoxins** [comment]
Thanks :)

**Comment by xin-hao-awx** [comment]
1. It seems that the new version `0.4.4` is not published to the crates.io
2. It will be awesome if we can publish a new version which includes https://github.com/eto-ai/lance/pull/810

Thanks~
