### ISSUE TITLE
Error in to_batches()

### ISSUE THREAD

**Issue by marsupialtail** [eto-ai/lance#750]
I try the tutorial, but I got this error when I tried to iterate through arrow batches: 

>>> sift1m
<lance.dataset.LanceDataset object at 0x7f087e76a820>
>>> sift1m.
sift1m.count_rows(           sift1m.schema
sift1m.create_index(         sift1m.sort_by(
sift1m.filter(               sift1m.take(
sift1m.get_fragments(        sift1m.to_batches(
sift1m.head(                 sift1m.to_table(
sift1m.join(                 sift1m.uri
sift1m.partition_expression  sift1m.version
sift1m.replace_schema(       sift1m.versions(
sift1m.scanner(              
>>> sift1m.to_batches()
<generator object LanceScanner.to_batches.<locals>._iterator at 0x7f09506f3970>
>>> a = next(sift1m.to_batches())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ziheng/miniconda3/envs/quokka-dev/lib/python3.8/site-packages/lance/dataset.py", line 486, in _iterator
    yield batch.record_batch
AttributeError: 'pyarrow.lib.RecordBatch' object has no attribute 'record_batch'

**Comment by changhiskhan** [comment]
thanks. let me repro and fix. in the meantime are you able to use to_reader?
