### ISSUE TITLE
Release intel and apple silicon wheels from Github Action

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#76]
# Problem Statement

Let's figure out how to build `x86_64` and `arm64` targets from Github Action mac runners. So that we can do release directly from GH actions. 

- [ ] Install / Build arrow / protobuf for both `x86_64` and `arm64`
- [ ] Build lance cpp SDK for both `x86_64` and `arm64`.
- [ ] Build python wheel via `cibuildwheel` for both `x86_64` and `arm64`

**Comment by Renkai** [comment]
I would take care of this. What's the current way to release a package to pypi? I don't see a release script in Github Actions.

**Comment by eddyxu** [comment]
I usually run the following on the root directory of the project.

```
python -m cibuildwheel --platform macos python
twine upload wheelhouse/pylance-*.whl
```

**Comment by Renkai** [comment]
So first line of build a installable package, second line upload it into [pypi.org](https://pypi.org/)?

**Comment by eddyxu** [comment]
> So first line of build a installable package, second line upload it into [pypi.org](https://pypi.org/)?

Yes, that's right.

**Comment by Renkai** [comment]
CI for M1 is not supported yet if we don't have a self-hosted m1 machine.
https://github.com/actions/runner-images/issues/2187
https://github.com/github/roadmap/issues/528

**Comment by Renkai** [comment]
Our [Python CI](https://github.com/eto-ai/lance/blob/main/.github/workflows/python.yml) now can build both `x86-linux` and `x86-darwin` wheels. We can turn it into a release script by some additional steps.
* add `TWINE_USERNAME` and `TWINE_PASSWORD` as action secretes of this repository
* execute `twine` with parameter `--non-interactive`
https://twine.readthedocs.io/en/stable/#environment-variables

**Comment by Renkai** [comment]
No idea why the Github team is not maintaining their [release action](https://github.com/actions/create-release) anymore. [This one](https://github.com/marketplace/actions/create-release) on the top of Google might be a good choice.

**Comment by eddyxu** [comment]
Do need to do it in one shot. But we can probably have cross-compiling to get m1 wheels from intel machine.

**Comment by Renkai** [comment]
Do you mean it's possible to cross-compile all the projects we need in the current ecosystem, including Arrow/Protobuf/c++ part of Lance?

**Comment by Renkai** [comment]
Discussed with @eddyxu , we can use the `arch` command of Mac.

**Comment by Renkai** [comment]
By what I read from `man arch`, the usage of `arch` is closer to select a subset of the binary when the binary is runnable on more than one architecture, not to change the output of a command.

**Comment by Renkai** [comment]
I feel this answer `cc --target=arm64-apple-darwin` is closer to what may solve the issue, but we have to ensure every dependency is build from source and we have always set this flag when necessary.

https://stackoverflow.com/questions/65361672/build-apple-silicon-binary-on-intel-machine

**Comment by Renkai** [comment]
It seems the only binary compiled by us is `liblance.dylib`, the `--target` flag can make an arm version for it. But for other dylibs, it's installed by other ways. If we want arm versions for them, it seems we have to find a way for each dylib individually, no idea about how to achieve it yet.

```
cibuildwheel --platform macos
...
...
+ delocate-listdeps /private/var/folders/l1/nzmv948n2gl_9b0y96dyxjzc0000gp/T/cibw-run-22fp83n4/cp310-macosx_x86_64/built_wheel/pylance-0.0.5-cp310-cp310-macosx_10_15_x86_64.whl && delocate-wheel --require-archs x86_64 -w /private/var/folders/l1/nzmv948n2gl_9b0y96dyxjzc0000gp/T/cibw-run-22fp83n4/cp310-macosx_x86_64/repaired_wheel /private/var/folders/l1/nzmv948n2gl_9b0y96dyxjzc0000gp/T/cibw-run-22fp83n4/cp310-macosx_x86_64/built_wheel/pylance-0.0.5-cp310-cp310-macosx_10_15_x86_64.whl
/Users/renkaige/renkai-lab/lance/cpp/build/liblance.dylib
/usr/local/Cellar/apache-arrow/9.0.0_1/lib/libarrow.900.0.0.dylib
/usr/local/Cellar/apache-arrow/9.0.0_1/lib/libarrow_dataset.900.0.0.dylib
/usr/local/Cellar/apache-arrow/9.0.0_1/lib/libparquet.900.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-c-auth.1.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-c-cal.1.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-c-common.1.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-c-compression.1.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-c-event-stream.1.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-c-http.1.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-c-io.1.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-c-mqtt.1.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-c-s3.1.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-c-sdkutils.1.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-checksums.1.0.0.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-cpp-sdk-cognito-identity.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-cpp-sdk-config.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-cpp-sdk-core.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-cpp-sdk-identity-management.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-cpp-sdk-s3.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-cpp-sdk-sts.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-cpp-sdk-transfer.dylib
/usr/local/Cellar/aws-sdk-cpp/1.9.330/lib/libaws-crt-cpp.dylib
/usr/local/Cellar/brotli/1.0.9/lib/libbrotlicommon.1.0.9.dylib
/usr/local/Cellar/brotli/1.0.9/lib/libbrotlidec.1.0.9.dylib
/usr/local/Cellar/brotli/1.0.9/lib/libbrotlienc.1.0.9.dylib
/usr/local/Cellar/lz4/1.9.4/lib/liblz4.1.9.4.dylib
/usr/local/Cellar/openssl@1.1/1.1.1q/lib/libcrypto.1.1.dylib
/usr/local/Cellar/openssl@1.1/1.1.1q/lib/libssl.1.1.dylib
/usr/local/Cellar/protobuf/21.5/lib/libprotobuf.32.dylib
/usr/local/Cellar/re2/20220601/lib/libre2.9.0.0.dylib
/usr/local/Cellar/snappy/1.1.9/lib/libsnappy.1.1.9.dylib
/usr/local/Cellar/thrift/0.16.0/lib/libthrift-0.16.0.dylib
/usr/local/Cellar/utf8proc/2.7.0/lib/libutf8proc.2.dylib
/usr/local/Cellar/zstd/1.5.2/lib/libzstd.1.5.2.dylib
```

**Comment by changhiskhan** [comment]
we have the intel mac wheel build up. Let's revisit the apple silicon build after GH makes M1/M2 runners available

**Comment by blackforestboi** [comment]
https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/
