### ISSUE TITLE
Document the difference between Lance filter API vs regular pyarrow

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/lance#784]
Because Lance is Rust based, we don't really have access to the Arrow C++ compute expressions. So instead, we use datafusion under the hood and you can pass in sql where clause strings. We should add a section in the documentation to clearly explain this difference. The function docstrings should also make this clear.

First reported in #783

**Comment by Ankit6989** [comment]
Hey changhiskhan I am interested in updating the documentation can you describe me what are the requirements and at which position I shall add about it in documentation section.
