### ISSUE TITLE
Error: `panicked at 'assertion failed: file_size - manifest_pos <= buf.len()'`

### ISSUE THREAD

**Issue by haoxins** [eto-ai/lance#856]
I write a program to convert parquet files into lance format.
It converted 600+ parquet files successfully and then the error occurred.

```
panicked at 'assertion failed: file_size - manifest_pos <= buf.len()'
```

**Comment by changhiskhan** [comment]
Hey thanks for filing an issue.
Can you help us try to understand better:

1. What version of Lance are you using?
2. What OS are you on?
3. How big is the file that triggered the bug?
4. When you say you're converting parquet files are you writing them all into the same lance dataset or are they separate?
5. If you share the code / stacktrace that would help
6. If the data is public that'd be even better

Thanks!

**Comment by haoxins** [comment]
> 1. What version of Lance are you using?

`0.4.8`

> 2. What OS are you on?

ubuntu 22.04

> 3. How big is the file that triggered the bug?

The each parquet file is `50mb ~ 150mb`

> 4. When you say you're converting parquet files are you writing them all into the same lance dataset or are they separate?

writing them all into the same lance dataset

> 5. If you share the code / stacktrace that would help

I write a simple cli to do this
https://github.com/haoxins/parquet2lance/blob/main/README.md

```
parquet2lance -i gs://bucket/parquet_dir -o gs://bucket/lance_dir -O
```

> 6. If the data is public that'd be even better

Sorry, it's private bucket :)

**Comment by wjones127** [comment]
> It seems that we should always read the whole manifest file here, why just read a range?

Agreed. It seems like we should check whether we need to make a second range request to get the rest of the manifest. I'm looking at implementing this now.
