### ISSUE TITLE
[I/O] Allow a flag for Scanner::to_batches() to return batches in non-deterministic order.

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/lance#861]
# Problem Statement

This allows more efficient usage of the prefetch queues, thus resulting better throughput in theory.

**Comment by changhiskhan** [comment]
This is basically buffer unordered?

**Comment by eddyxu** [comment]
Yep, excatly.

**Comment by wjones127** [comment]
IIUC right now we create just one IO thread for performing the Scan here:

https://github.com/eto-ai/lance/blob/2090d7f19bfc5891529ef7a2cabd3063ce29c89e/rust/src/io/exec/scan.rs#L72

Would part of this ticket be adding additional IO threads? Or is there parallelism that I am missing?
