### ISSUE TITLE
parallel reads seems to be turned off in lance?

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/lance#93]
I ran the label distribution query against coco for parquet and lance. For parquet, the total CPU time was greater than the Wall time, but for lance that was not the case. I vaguely remember discussing this before, not sure if it's already a known issue.

**Comment by eddyxu** [comment]
Yes, currently we disabled parallel reads when LIMIT / OFFSET is provided for simpler design for Limit exector. We can revise this decision though.
